language: c
sudo: false
compiler:
  - clang
  - gcc
script:
  - git clone https://github.com/andschwa/c-unit-test.git test
  - gcc -O -Wall -Werror -std=gnu99 -DTEST_DEBUG -DHASHT_DEBUG -o test_hasht hasht.c lookup3.c test_hasht.c test/test.c
  - ./test_hasht
